[package]
name = "morgan-storage-controller"
version = "0.15.3"
description = "Morgan storage controller"
authors = ["Morgan Maintainers <maintainers@morgan.com>"]
repository = "https://github.com/morgan-labs/morgan"
license = "Apache-2.0"
homepage = "https://morgan.com/"
edition = "2018"

[dependencies]
log = "0.4.2"
morgan-logger = { path = "../../logger", version = "0.15.3"     }
morgan-interface = { path = "../../interface", version = "0.15.3"     }
morgan-storage-api = { path = "../storage_api", version = "0.15.3"     }

[lib]
name = "morgan_storage_controller"
crate-type = ["lib", "cdylib"]
